name: Run Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create audio input folder
        run: mkdir -p audio_inputs_ci

      - name: Copy .mp3 files into audio_inputs
        run: cp audio_inputs/*.mp3 audio_inputs

      - name: Run production script
        run: python process_audio.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: prod
